### ISSUE TITLE
JLBH - Latency vs Load

### ISSUE THREAD

**Issue by toaler** [OpenHFT/Chronicle-Core#11] opened 2016-05-05 17:01 UTC
We were interested in using JLBH for testing how a features latencies scale while under loads (ie. 1, 2, 4, 8, etc threads of execution).

I don't see that JLBH current allows the number of threads to be ramped up.  It seems like the code could be modified to run the test task concurrently.

I'm curious if JLBH by design didn't support higher loads for a reason?  What is your take on this?  If there isn't a fundamental issue with supporting higher loads, we may try and make the necessary change to support this feature.  Any guidance for us before trying this out?

**Comment by peter-lawrey** [comment] 2016-05-05 19:39
The intent is that the init() should create components which as as multi -
threaded as you need. The test harness could be extended to create multiple
threads for you but at the moment you need to do that.

Regards, Peter.
On 5 May 2016 6:01 pm, "Brian Toal" <notifications@github.com> wrote:

We were interested in using JLBH for testing how a features latencies scale
while under loads (ie. 1, 2, 4, 8, etc threads of execution).

I don't see that JLBH current allows the number of threads to be ramped up.
It seems like the code could be modified to run the test task concurrently.

I'm curious if JLBH by design didn't support higher loads for a reason?
What is your take on this? If there isn't a fundamental issue with
supporting higher loads, we may try and make the necessary change to
support this feature. Any guidance for us before trying this out?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/OpenHFT/Chronicle-Core/issues/11>

**Comment by danielshaya** [comment] 2016-05-05 21:31
As Peter explained the JLBH is already designed to handle multi threaded
use cases.

So when you get the call into run() you can allocate a task to a single
thread or to many threads at that point.

I assume you would like to build in the functionality to call the run()
method x times for a given number of threads - am I correct?

If so that sounds like a very interesting and possibly useful enhancement
for certain use cases.

You would have to think about how probes would be handled - would you want
them on a per thread basis or across all threads.

I would certainly be interested in a fuller explanation of what you would
like to build and would be very happy to extend JLBH if you can make a
useful contribution to the community.

Cheers
Daniel

**Comment by toaler** [comment] 2016-05-05 23:33
Thanks guys from the prompt turn around time.  We may take a shot at this.  However have found iago provides this functionality and maybe suitable for our current performance testing needs.  Due to the tight project time constraints we may be forced to go with iago.  We'll keep you posted.

**Comment by peter-lawrey** [comment] 2016-06-27 12:47
Closing as it has been more than a month.

**Closed by peter-lawrey** 2016-06-27 12:47 UTC

**Comment by hft-team-city** [comment] 2020-10-21 16:40
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
